[tool.poetry]
name = "oeis"
version = "0.1.0"
description = ""
authors = ["Reid Hochstedler <reidhoch@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "20.8b1"
hypothesis = "^6.8"
mypy = "^0.812"
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
